#KSriHarsha
wedaa-tech/wda-server pull request #2
Opened 2023-08-15 08:12 UTC by raxkumar-wedaa

- Added Api Calls for Ref Archs

2023-08-15 11:10 UTC, raxkumar-wedaa reviewed
Review OK!
(#rakesh)

2023-08-16 06:22 UTC, rohith-wedaa requested changes

2023-08-16 06:22 UTC, rohith-wedaa commented on model/refArchitecture.js
> +        unique : false,
Name must also be unique. There cannot be more than 1 reference architecture having **Full Stack** name, which causes ambiguity.

2023-08-16 06:22 UTC, rohith-wedaa commented on model/refArchitecture.js
> +    refArch_id :{
let's use mongo's `_id`.

2023-08-16 06:22 UTC, rohith-wedaa commented on model/refArchitecture.js
> +    },
let's add one more field called `type`. there can be reference architectures for application, infrastructure, data pipelines or devsecops.

2023-08-16 08:00 UTC, rohith-wedaa approved these changes

2023-08-16 08:00 UTC, merged