Feature/credit service
wedaa-tech/wda-server pull request #74
Opened 2024-07-17 10:01 UTC by harsha-wedaa

Credit service sync with wedaa-Server.

2024-07-17 17:35 UTC, rohith-wedaa requested changes

2024-07-17 17:35 UTC, rohith-wedaa commented on src/utils/creditcore.js
> +async function addTransactioLog(data, accessToken) {
**addTransactioLog** typo - **n** missing

2024-07-17 17:35 UTC, rohith-wedaa commented on src/designer/core.js
> +        await creditCore.updateUserCredit(credits,accessToken)
put this block in a service method, with required arguments.

2024-07-18 18:10 UTC, raxkumar-wedaa commented on src/designer/core.js
> +    }
Updated this to 
const dbmlCount = Object.values(services).filter(service => service.dbmlData).length;

2024-07-18 18:21 UTC, raxkumar-wedaa commented on src/designer/core.js
> +        accessToken:accessToken
Remove this from here and adding a new creditContext

2024-07-19 05:59 UTC, raxkumar-wedaa commented on src/services/blueprintService.js
> +exports.getData = async function (req, res) {
Updated the method name to getMetadata

2024-07-23 12:25 UTC, rohith-wedaa approved these changes

2024-07-23 12:25 UTC, merged