Feature/h2
wedaa-tech/wda-server pull request #80
Opened 2024-09-24 04:41 UTC by vamshi-ra

Added extendability to H2

2024-09-24 04:47 UTC, raxkumar-wedaa reviewed
Review OK!

2024-11-07 15:21 UTC, rohith-wedaa requested changes

2024-11-07 15:21 UTC, rohith-wedaa commented on src/utils/jsonToJdl.js
> +            console.info(applicationError);
console.error()

2024-11-07 15:21 UTC, rohith-wedaa commented on src/utils/jsonToJdl.js
> +            applications[i].prodDatabaseType !== undefined && applications[i].prodDatabaseType !== 'h2Memory' &&
if possible positive checks

2024-11-07 15:21 UTC, rohith-wedaa commented on src/utils/jsonToJdl.js
> +        }
combine conditions for database

2024-11-07 15:21 UTC, rohith-wedaa commented on src/utils/jsonToJdl.js
> +        ${databaseType !== 'no' && databaseType !== 'h2Memory' ? `databasePort ${applications[i].databasePort}` : ''}
merge with L161

databaseType === 'sql'

2024-12-09 08:57 UTC, rohith-wedaa approved these changes

2024-12-09 08:57 UTC, merged